Implement Wallet.create_pay_to_contract_address
chaintope/tdk pull request #22
Opened 2024-07-21 17:16 UTC by Yamaguchi

### Description

This PR implements to generate Pay-To-Contract address.

### Notes to the reviewers

### Changelog notice

### Checklists

#### All Submissions:

* [ ] I've signed all my commits
* [ ] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2024-07-21 17:21 UTC, Yamaguchi commented on crates/wallet/Cargo.toml
> +curv-kzen = { git = "https://github.com/Yamaguchi/curv", branch = "make_GE_public_interface_for_sec256k1" }
curvのライブラリに一部問題があるため、forkしたものを使用しています。
fork元のリポジトリにPRは投げています。
https://github.com/ZenGo-X/curv/pull/185

2024-07-22 05:18 UTC, Yamaguchi commented on crates/wallet/src/wallet/mod.rs
> +const CONTRACT_MAX_SIZE: usize = 256;
Contractの最大バイト数を暫定で256としています。(アプリ側でチェックするのであれば、ここでは不要かもしれません)

2024-07-22 12:13 UTC, Yamaguchi commented
curvをやめて、secp256k1のメソッドを使用するように変更してます。

2024-07-23 14:11 UTC, rantan requested changes

2024-07-23 14:11 UTC, rantan commented on crates/wallet/src/wallet/mod.rs
> +    pub fn create_pay_to_contract_commitment(
と思ったけど、`pay_to_contract_key` の `add_exp_tweak` でスカラ値を扱うときに剰余しているぽい？

2024-07-29 07:50 UTC, merged