Balance for p2c
chaintope/tdk pull request #28
Opened 2024-08-05 04:29 UTC by Yamaguchi

### Description

The PR adds an update to include coins transferred to a P2C address in the balance.

### Checklists

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [x] I've added tests for the new feature
* [x] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

2024-08-07 06:57 UTC, rantan requested changes

2024-08-07 06:57 UTC, rantan commented on crates/wallet/src/wallet/mod.rs
> +    pub fn insert_descriptor(
外からは呼ば差なそうなので pub をつけなくてもよいかと思いました。

2024-08-07 06:57 UTC, rantan commented on crates/wallet/tests/common.rs
> +    let payment_base =
wallet.store_contract() でwallet に追加するコントラクトのpayment_baseは、wallet で管理している秘密鍵に対応する公開鍵であることを想定していました。そうでないと、p2cアドレスあてのUTXOを送金できないので。

仕様には記載していませんでしたが、store_contract()でうけとった payment_base がウォレットで管理している鍵でない場合、エラーにするバリデーション処理を加えた方が安全な気がしました。
どう思われますか？

2024-08-07 07:00 UTC, rantan commented on crates/wallet/src/wallet/mod.rs
> +            let _ = self.insert_descriptor(KeychainKind::External, descriptor);
すでに wallet に KeychainKind::External な keychain が設定されている場合、新たに追加するのではなく、上書きしてしまうことになりませんか？

2024-08-10 16:55 UTC, Yamaguchi commented on crates/wallet/src/wallet/mod.rs
> +    pub fn insert_descriptor(
別の指摘に従い、メソッド自体を削除しました。

2024-08-10 16:56 UTC, Yamaguchi commented on crates/wallet/tests/common.rs
> +    let payment_base =
バリデーション処理を追加しました。

2024-08-10 16:57 UTC, Yamaguchi commented on crates/wallet/src/wallet/mod.rs
> +            let _ = self.insert_descriptor(KeychainKind::External, descriptor);
上記の理由からinsert_descriptorを使わず、indexerにpayment_baseと対応するp2c scriptの対応をマップ化して保持するように修正しました。

2024-08-18 12:21 UTC, Yamaguchi commented on crates/wallet/tests/common.rs
> +    let payment_base =
52a4dc5eeca5264b9bcdb609ac6d2c3c151bccb1でメソッドの位置を変更しました。

2024-09-02 08:07 UTC, rantan commented
#31 でマージしました。

2024-09-02 08:07 UTC, closed without merging